version: "3.7"

services:
  zyvue:
    networks:
      - frontend
    image: senthilsweb/zyvue:latest
    container_name: zyvue
    restart: unless-stopped
    tty: true
    ports:
      - "7777:3000"
    environment:
      - REST_ENDPOINT=http://zygo:3000/api/
networks:
  frontend: