version: "3.7"

services:
  zyvue:
    networks:
      - frontend
    image: senthilsweb/zyvue:latest
    container_name: zyvue
    restart: unless-stopped
    tty: true
    ports:
      - "5000:3000"
    environment:
      - REST_ENDPOINT="http://18.189.3.157:1337/api"
      - API_KEY=
networks:
  frontend: null
